Revert "Bump werkzeug from 2.3.7 to 2.3.8 (#135)"
This reverts commit d0c163b908cd043873114f72ba185bbaa09331a3.

This seems to break compatibility with flask-session too. It causes the
following exception:

    [2023-11-20 09:31:15 +0000] [9] [ERROR] Error handling request /healthcheck
    Traceback (most recent call last):
      File "/venv/lib64/python3.11/site-packages/gunicorn/workers/gthread.py", line 282, in handle
        keepalive = self.handle_request(req, conn)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask/app.py", line 2552, in __call__
        return self.wsgi_app(environ, start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask/app.py", line 2532, in wsgi_app
        response = self.handle_exception(e)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
        return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                    ^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask_restx/api.py", line 674, in error_router
        return original_handler(e)
               ^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
        response = self.full_dispatch_request()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask/app.py", line 1826, in full_dispatch_request
        return self.finalize_request(rv)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask/app.py", line 1847, in finalize_request
        response = self.process_response(response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib64/python3.11/site-packages/flask/app.py", line 2344, in process_response
        self.session_interface.save_session(self, ctx.session, response)
      File "/venv/lib64/python3.11/site-packages/flask_session/sessions.py", line 573, in save_session
        response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
      File "/venv/lib64/python3.11/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
        dump_cookie(
      File "/venv/lib64/python3.11/site-packages/werkzeug/http.py", line 1303, in dump_cookie
        if not _cookie_no_quote_re.fullmatch(value):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: cannot use a string pattern on a bytes-like object